# Generated by Django 5.0.1 on 2024-02-19 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
