# Generated by Django 5.0.1 on 2024-03-12 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_wishlist_product_remove_wishlist_user_and_more'),
        ('user', '0004_product_purchasehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterModelOptions(
            name='purchasehistory',
            options={},
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
